# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0010_delete_dichvu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopdong',
            options={'verbose_name': 'Điều Khoản Công Ty', 'verbose_name_plural': 'Điểu khoản công ty'},
        ),
    ]
