# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0006_alter_notification_loai_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Thông Báo', 'verbose_name_plural': 'Thông Báo'},
        ),
    ]
