# Generated by Django 4.2.3 on 2024-05-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0010_remove_baitimviec_image_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='baitimviec',
            name='ly_do',
            field=models.CharField(default='Vi phạm tiêu chuẩn cộng đồng', max_length=150),
        ),
    ]
