# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0013_alter_baitimviec_ly_do'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baitimviec',
            options={'verbose_name': 'Bài Tìm Việc', 'verbose_name_plural': 'Bài Tìm Việc'},
        ),
    ]
