# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_alter_giaodich_trang_thai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giaodich',
            options={'verbose_name': 'Giao Dịch', 'verbose_name_plural': 'Giao Dịch'},
        ),
    ]
