# Generated by Django 4.2.3 on 2024-05-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_rename_khu_vuc_baithue_dia_chi'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithue',
            name='ly_do',
            field=models.CharField(default='Vi phạm tiêu chuẩn cộng đồng', max_length=150),
        ),
    ]
