# Generated by Django 4.2.3 on 2024-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_baithue_ly_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithue',
            name='da_duyet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baithue',
            name='ly_do',
            field=models.CharField(default='', max_length=150),
        ),
    ]
