# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_alter_baithue_da_duyet_alter_baithue_ly_do'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baithue',
            options={'verbose_name': 'Bài Thuê', 'verbose_name_plural': 'Bài Thuê'},
        ),
    ]
