# Generated by Django 4.2.3 on 2024-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_alter_baithue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithue',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
