# Generated by Django 4.2.3 on 2024-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_user_anh_dai_dien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khachhang',
            options={'verbose_name': 'Khách Hàng', 'verbose_name_plural': 'Khách Hàng'},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'verbose_name': 'Nhân Viên', 'verbose_name_plural': 'Nhân Viên'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='place_issued',
        ),
    ]
